Reader/Reader/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView, HomeSearch, CreateUserModalView
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('account/', include('login.urls')),
    path('blog/', include('blog.urls')),
    path('chatbot/', include('chatbot.urls')),
    # path('model/', include('recommendation.urls')),
    path('profile/', include('myprofile.urls')),
    path('', HomeView.as_view(), name='home'),
    path('signup/', CreateUserModalView.as_view(), name='signup'),
    path('search/', HomeSearch, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Reader/blog/urls.py
from django.urls import path, re_path
from .views import PostList, PostSingle, AddComment, Sub, Update, Delete, SubUpdate, SubDelete, PostDelete, PostUpdate, PostSearch


app_name = 'blog'
urlpatterns = [
    path(r'sub/update/<int:pk>/', SubUpdate.as_view(), name='sub_update'),
    path(r'sub/delete/<int:pk>/', SubDelete, name='sub_delete'),
    path(r'update/<int:pk>/', Update.as_view(), name='comment_update'),
    path(r'delete/<int:pk>/', Delete, name='comment_delete'),
    path(r'sub/<int:pk>/', Sub.as_view(), name='sub'),
    path(r'comment/<int:pk>/', AddComment.as_view(), name='comment'),
    path(r'post/delete/<int:pk>/', PostDelete, name='post_delete'),
    path(r'post/update/<int:pk>/', PostUpdate.as_view(), name='post_update'),
    path(r'single/post/<int:pk>/', PostSingle.as_view(), name='single'),
    path(r'search/', PostSearch, name='search'),
    re_path(r'(?P<slug>[-\w]+)/(?P<page>\d+)/$', PostList.as_view(), name='blog_page'),
    re_path(r'(?P<slug>[-\w]+)/$', PostList.as_view(), name='blog'),
]

Reader/book/urls.py
from django.urls import path, re_path
from .room_views import BookView, RoomList, WishRoom, RoomIn, RoomSingle, AddRoomComment, DeleteComment, UpdateComment, UpdateProgress, RoomSort
from .book_views import BookList, WishBook, BookSingle, BookReview, DeleteReview, UpdateReview, MakeRoom


app_name = 'book'
urlpatterns = [
    re_path(r'room/update/progress/(?P<slug_sub>[-\w]+)/(?P<doc_id>[-\w]+)/$', UpdateProgress.as_view(), name='update_progress'),
    re_path(r'room/inside/(?P<slug_sub>[-\w]+)/(?P<pk>\d+)/(?P<in>\d+)/$', RoomIn.as_view(), name='room_modal_in'),
    re_path(r'room/inside/(?P<slug_sub>[-\w]+)/(?P<pk>\d+)/$', RoomIn.as_view(), name='room_in'),
    re_path(r'update/(?P<col_id>[-\w]+)/(?P<doc_id>[-\w]+)/$', UpdateComment.as_view(), name='comment_update'),
    re_path(r'delete/(?P<col_id>[-\w]+)/(?P<doc_id>[-\w]+)/$', DeleteComment.as_view(), name='comment_delete'),
    re_path(r'room/(?P<doc_id>[-\w]+)/$', AddRoomComment.as_view(), name='room_add_comment'),
    re_path(r'room/(?P<slug_main>[-\w]+)/(?P<slug_sub>[-\w]+)/(?P<pk>\d+)/$', RoomSingle.as_view(), name='room_single'),
    re_path(r'room/(?P<slug_sub>[-\w]+)/(?P<pk>\d+)/$', WishRoom.as_view(), name='wish_room'),
    re_path(r'sort/(?P<slug_sub>[-\w]+)/$', RoomSort.as_view(), name='room_sort'),
    re_path(r'room/(?P<slug_main>[-\w]+)/(?P<slug_sub>[-\w]+)/$', RoomList.as_view(), name='room_list'),
    re_path(r'make/(?P<slug_main>[-\w]+)/(?P<slug_sub>[-\w]+)/(?P<pk>\d+)/$', RoomList.as_view(), name='room_list_'),
    path('', BookView.as_view(), name='book'),
] + [
    re_path(r'make/(?P<slug_sub>[-\w]+)/(?P<pk>\d+)/$', MakeRoom.as_view(), name='make_room'),
    path('delete/<int:pk>/', DeleteReview, name='delete'),
    re_path(r'update/$', UpdateReview.as_view(), name='update'),
    re_path(r'single/(?P<slug_item>[-\w]+)/$', BookSingle.as_view(), name='book_single'),
    re_path(r'review/(?P<slug_item>[-\w]+)/$', BookReview.as_view(), name='book_review'),
    path('wish/<int:pk>/', WishBook.as_view(), name='book_wish'),
    re_path(r'(?P<slug_main>[-\w]+)/(?P<slug_sub>[-\w]+)/(?P<page>\d+)/$', BookList.as_view(), name='book_list'),
]

Reader/book/models.py
from django.db import models
from taggit.managers import TaggableManager
from login.models import User
from django.urls import reverse_lazy


# Create your models here.
class MainCategory(models.Model):
    code = models.IntegerField(default=0, blank=True, null=True)
    name = models.CharField('NAME', max_length=100, blank=True)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, blank=True, null=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    code = models.IntegerField(default=0, blank=True, null=True)
    name = models.CharField('NAME', max_length=100)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, blank=True, null=True)
    main = models.ForeignKey(MainCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Book(models.Model):
    # find key
    key = models.IntegerField(default=0)
    name = models.CharField('NAME', max_length=100, blank=True)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, blank=True, null=True)

    explain = models.TextField('EXPLAIN', blank=True)
    score = models.FloatField(default=0)
    page = models.IntegerField(default=0)
    code = models.FloatField(default=0)
    tag = TaggableManager(blank=True)

    author = models.CharField('AUTHOR', max_length=100, blank=True)
    publication = models.CharField('PUBLICATION', max_length=100, blank=True)
    publication_date = models.IntegerField(default=0)
    create_dt = models.DateTimeField('CREATE_DATE', auto_now_add=True)

    # 이미지 필드
    image = models.ImageField(upload_to='book/%Y/%m', blank=True, null=True)

    # 외래키 필드
    category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    wish = models.ManyToManyField(User, blank=True, null=True)

    class Meta:
        db_table = 'books'
        verbose_name = 'book'
        verbose_name_plural = 'books'
        ordering = ('-create_dt',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('book:book_single', args=(self.slug,))


class Review(models.Model):
    subject = models.TextField('SUBJECT', blank=True, null=True)
    explain = models.TextField('EXPLAIN')
    score = models.FloatField(default=0, blank=True)
    create_dt = models.DateTimeField('CREATE_DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY_DATE', auto_now=True)

    # 외래키
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'reviews'
        verbose_name = 'review'
        verbose_name_plural = 'reviews'
        ordering = ('-create_dt',)

Reader/book/forms.py
from django import forms


class CommentForm(forms.Form):
    contents = forms.CharField(widget=forms.Textarea)


class RoomForm(forms.Form):
    subject = 

Reader/book/templates/book/book_book.html
{% extends "book/book.html" %}

{% load static %}

{% block extra-style %}
    <style>
        .fa.fa-heart-o.active  {
            color: #f00 !important;
        }
        button .fa.fa-heart-o.list  {
            color: #888888 !important;
        }
        .productListSingle .media .media-body .btn-group .btn-default:focus {
             border-radius: 0;
             width: 35px;
             height: 35px;
             line-height: 33px !important;
             padding: 0;
             text-align: center;
             margin-right: 7px;
             border: 1px solid #d0d0d0;
             background: transparent;
             transition: all 0.3s ease-in-out;
        }
        .my.pagination > .active > a, 
        .my.pagination > .active > span, 
        .my.pagination > .active > a:hover, 
        .my.pagination > .active > span:hover, 
        .my.pagination > .active > a:focus, 
        .my.pagination > .active > span:focus {
            background: #47bac1;;
            border-color: #47bac1;
        }
    </style>
{% endblock %}

{% block sub_category %}
{% for sub_category in category.subcategory_set.all %}
{% if sub_category.slug == slug_sub %}
<li><a style="color:#47bac1;" href="{% url 'book:book_list' category.slug sub_category.slug page %}"><i class="fa fa-caret-right" aria-hidden="true"></i>{{ sub_category }}<span>
    ({{ sub_category.book_set.count }})</span></a></li>
{% else %}
<li><a href="{% url 'book:book_list' category.slug sub_category.slug page %}"><i class="fa fa-caret-right" aria-hidden="true"></i>{{ sub_category }}<span>
    ({{ sub_category.book_set.count }})</span></a></li>
{% endif %}
{% endfor %}
{% endblock %}

{% block sort %}
{% endblock %}

{% block ajax %}
{% endblock %}

{% block grid %}
<button type="button" class="btn btn-default" onclick="window.location.href='{% url 'book:room_list' slug_main slug_sub %}'"><i class="fa fa-th" aria-hidden="true"></i><span style="font-size:14px;">독서방</span></button>
{% endblock %}
{% block list %}
<button type="button" class="btn btn-default active" onclick="window.location.href=''"><i class="fa fa-th-list" aria-hidden="true"></i><span>도서</span></button>
{% endblock %}

{% block item_list %}
<div id="book_list">
  <div class="row productListSingle">
    {% with wish_list=user.book_set.all %}
    {% for book in books %}
    <div class="col-sm-12 ">
      <div class="media flex-wrap productBox">
        <div class="media-left">
          <div class="productImage clearfix">
            <img src="{{ book.image.url }}" style="border-radius:7px;" alt="products-img">
              <div class="productMasking">
                <ul class="list-inline btn-group" role="group">
                  {% if not user.is_active %}
                  <li><a class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart-o"></i></a></li>
                  {% elif book in wish_list %}
                  <li><a id="wish_fade{{ book.key }}" class="btn btn-default"><div id="wish_div_fade{{ book.key }}"><i class="fa fa-heart-o active"></i></div></a></li>
                  {% else %}
                  <li><a id="wish_fade{{ book.key }}" class="btn btn-default"><div id="wish_div_fade{{ book.key }}"><i class="fa fa-heart-o"></i></div></a></li>
                  {% endif %}
                  <li><i class="fa fa-asterisk"></i></li>
                  <li><a class="btn btn-default" data-toggle="modal" href="#book{{ book.key }}" ><i class="fa fa-eye"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></h4>
            <p>{{ book.explain }}
            <br><br>
            {% load taggit_templatetags2_tags %}
            {% get_tags_for_object book as "tags" %}
            <span style="color:#47bac1;">
            {% for tag in tags %}
            #{{ tag.name }}&nbsp;
            {% endfor %}
            </span>
            </p>
            <div class="btn-group" role="group">
              {% if not user.is_active %}
              <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
              {% elif book in wish_list %}
              <button id="wish{{ book.key }}" type="button" class="btn btn-default"><div id="wish_div{{ book.key }}"><i class="fa fa-heart-o active"></i></div></button>
              {% else %}
              <button id="wish{{ book.key }}" type="button" class="btn btn-default list"><div id="wish_div{{ book.key }}"><i class="fa fa-heart-o"></i></div></button>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <script type="text/javascript">
          $(document).ready(function(){
              $('#wish{{ book.key }}, #wish_fade{{ book.key }}').click(function(){
                  $.ajax({
                      type: 'GET',
                      url : "{% url 'book:book_wish' book.key %}",
                      success: function(data){
                          $('#wish_div{{ book.key }}').html(data)
                          $('#wish_div_fade{{ book.key }}').html(data)
                      }
                  });
              });
          });
      </script>
    {% endfor %}
    {% endwith %}
  </div>
</div>
{% endblock %}

{% block pagination %}
{% if is_page %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center my">
    {% if present_page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% url 'book:book_list' slug_main slug_sub present_page_obj.previous_page_number %}" aria-label="Previous">
        <span style="color:#47bac1;">&laquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Previous">
        <span style="color:#808080;">&laquo;</span>
      </a>
    </li>
    {% endif %}
      
    {% for idx in page_obj.page_range %}
    {% if idx == present_page %}
    <li class="page-item active">
      <a class="page-link" href="{% url 'book:book_list' slug_main slug_sub idx %}">{{ idx }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="{% url 'book:book_list' slug_main slug_sub idx %}"><span style="color:#47bac1;">{{ idx }}</span></a>
    </li>
    {% endif %}
    {% endfor %}
      
    {% if present_page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'book:book_list' slug_main slug_sub present_page_obj.next_page_number %}" aria-label="Next">
        <span style="color:#47bac1;">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Next">
        <span style="color:#808080;">&raquo;</span>
      </a>
    </li>
    {% endif %}
     
  </ul>
</nav>
{% endif %}
{% endblock %}

Reader/book/templates/book/book_room.html
{% extends "book/book.html" %}

{% load static %}

{% block extra-style %}
    <style>
        .fa.fa-heart-o.active  {
            color: #f00 !important;
        }
        .masking-hover, .imageBox .productImage .productMasking.end, .whiteSection .featuredProducts .slide .productImage .productMasking, .mainContent .featuredProducts .slide .productImage .productMasking, .productsContent .productBox .productImage .productMasking.end, .whiteSection .featuredCollection .thumbnail .imageWrapper .masking, .mainContent .featuredCollection .thumbnail .imageWrapper .masking, .productListSingle .media .media-left .maskingImage {
            background-color: rgba(244, 92, 93, 0.9) !important;
        }
    </style>
{% endblock %}

{% block sub_category %}
{{ block.super }}
{% endblock %}

{% block sort %}
{{ block.super }}
{% endblock %}

{% block ajax %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#sort').click(function(){
            var pk = $('.select-drop option:selected').val()
            
            $.ajax({
                type: 'GET',
                url : "{% url 'book:room_sort' slug_sub %}",
                data: {'pk':pk},
                success: function(data){
                    $('#room_list').html(data)
                }
            });
            $('.select-drop').append('<option value="0">전체</option>')
            $('.select-drop').append('<option value="1">인원 모집 중</option>')
            $('.select-drop').append('<option value="2">마감 임박</option>')
            $('.select-drop').append('<option value="3">마감</option>')
        });
    });
</script>
{% endblock %}

{% block grid %}
<button type="button" class="btn btn-default active" onclick="window.location.href='{% url 'book:room_list' slug_main slug_sub %}'"><i class="fa fa-th" aria-hidden="true"></i><span style="font-size:14px;">독서방</span></button>
{% endblock %}
{% block list %}
<button type="button" class="btn btn-default" onclick="window.location.href='{% url 'book:book_list' slug_main slug_sub page %}'"><i class="fa fa-th-list" aria-hidden="true"></i><span>도서</span></button>
{% endblock %}
    
{% block item_list %}
<div id="room_list">
<div class="row">
    {% for room in rooms %}
    <div class="col-md-6 col-lg-4">
      <div class="productBox">
        <div class="productImage clearfix">
          <img src="{{ room.image }}" style="border-radius:7px;" alt="products-img">
          
          {% if 0 >= room.d_day or room.user|length == room.full %}
          <div class="productMasking end">
          {% else %}
          <div class="productMasking">
          {% endif %}
            {% if 0 >= room.d_day or room.user|length == room.full %}
            <ul>
              <h3 style="font-size:13px; color:#a52a2a;">이미 마감된 방입니다.</h3>
            </ul>
            {% else %}
            <h3 style="color:#fff; padding-top:60px; padding-left:41px;">D-{{ room.d_day }}</h3>
            <ul class="list-inline btn-group" role="group">
              <!-- wish button -->  
              {% if user.email in room.wish %}
              <li><a id="wish_fade{{ room.pk }}" class="btn btn-default"><div id="wish_div_fade{{ room.pk }}"><i class="fa fa-heart-o active"></i></div></a></li>
              {% else %}
              <li><a id="wish_fade{{ room.pk }}" class="btn btn-default"><div id="wish_div_fade{{ room.pk }}"><i class="fa fa-heart-o"></i></div></a></li>
              {% endif %}
              <!-- 방 가입 버튼 -->  
              {% if not user.is_active %}
              <li><a class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-sign-in"></i></a></li>
              {% elif user.email in room.user or user.email == room.leader %}
              <li><a href="javascript:void(0)" class="btn btn-default"><i class="fa fa-check"></i></a></li>
              {% else %}
              <li><a id="inside_fade{{ room.pk }}" href="javascript:void(0)" class="btn btn-default" data-toast data-toast-type="success" data-toast-position="topRight" data-toast-icon="icon-circle-check" data-toast-title="안내" data-toast-message="독서 모임에 합류하셨습니다." class="btn btn-default"><div id="inside_div_fade{{ room.pk }}"><i class="fa fa-sign-in"></i></div></a></li>
              {% endif %}
              <!-- 자세히보기 --> 
              <li><a class="btn btn-default" data-toggle="modal" href="#room{{ room.pk }}" ><i class="fa fa-eye"></i></a></li>
            </ul>
            {% endif %}
          </div>
        </div>
        <div class="productCaption clearfix">
          <a href="{{ room.get_absolute_url }}">
            <h5>{{ room.subject }}</h5>
          </a>
          {% if 0 >= room.d_day or room.user|length == room.full %}
          <h3 style="font-size:14px; color:#a52a2a;">마감</h3>
          {% elif user.email in room.user or user.email == room.leader %}
          <h3>{{ room.user|length }}/{{ room.full }}&nbsp;&nbsp;<span style="color:#47bac1; font-size:14px;">이미 가입된 방입니다.</span></h3>
          {% elif 10 >= room.d_day %}
          <h3>{{ room.user|length }}/{{ room.full }}&nbsp;&nbsp;<span style="color:#47bac1; font-size:14px;">마감임박</span></h3>
          {% elif room.d_day > 10 %}
          <h3>{{ room.user|length }}/{{ room.full }}</h3>
          {% endif %}
        </div>
      </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#wish{{ room.pk }}, #wish_fade{{ room.pk }}').click(function(){
                $.ajax({
                    type: 'GET',
                    url : "{% url 'book:wish_room' slug_sub room.pk %}",
                    success: function(data){
                        $('#wish_div_fade{{ room.pk }}').html(data)
                    }
                });
            });
        });
        
        $(document).ready(function(){
            $('#inside_fade{{ room.pk }}').click(function(){
                $.ajax({
                    type: 'GET',
                    url : "{% url 'book:room_in' slug_sub room.pk %}",
                    success: function(data){
                        $('#inside_div_fade{{ room.pk }}').html(data)
                    }
                });
            });
        });
    </script>
    {% endfor %}
</div>
</div>
{% endblock %}

Reader/book/templates/book/check_wish.html
<i class="fa fa-heart-o active"></i>

Reader/book/templates/book/check_wish_book.html
<i class="fa fa-heart-o active"></i>

Reader/book/templates/book/room_inside.html
<i class="fa fa-check"></i>

Reader/book/templates/book/room_sort.html
<div class="row">
    {% for room in rooms %}
    <div class="col-md-6 col-lg-4">
      <div class="productBox">
        <div class="productImage clearfix">
          <img src="{{ room.image }}" style="border-radius:7px;" alt="products-img">
          
          {% if 0 >= room.d_day or room.user|length == room.full %}
          <div class="productMasking end">
          {% else %}
          <div class="productMasking">
          {% endif %}
            {% if 0 >= room.d_day or room.user|length == room.full %}
            <ul>
              <h3 style="font-size:13px; color:#a52a2a;">이미 마감된 방입니다.</h3>
            </ul>
            {% else %}
            <h3 style="color:#fff; padding-top:60px; padding-left:41px;">D-{{ room.d_day }}</h3>
            <ul class="list-inline btn-group" role="group">
              <!-- wish button -->  
              {% if not user.is_active %}
              <li><a class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart-o"></i></a></li>
              {% elif user.email in room.wish %}
              <li><a id="wish_fade{{ room.pk }}" class="btn btn-default"><div id="wish_div_fade{{ room.pk }}"><i class="fa fa-heart-o active"></i></div></a></li>
              {% else %}
              <li><a id="wish_fade{{ room.pk }}" class="btn btn-default"><div id="wish_div_fade{{ room.pk }}"><i class="fa fa-heart-o"></i></div></a></li>
              {% endif %}
              <!-- 방 가입 버튼 -->  
              {% if not user.is_active %}
              <li><a class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-sign-in"></i></a></li>
              {% elif user.email in room.user or user.email == room.leader %}
              <li><a href="javascript:void(0)" class="btn btn-default"><i class="fa fa-check"></i></a></li>
              {% else %}
              <li><a id="inside_fade{{ room.pk }}" href="javascript:void(0)" class="btn btn-default" data-toast data-toast-type="success" data-toast-position="topRight" data-toast-icon="icon-circle-check" data-toast-title="안내" data-toast-message="독서 모임에 합류하셨습니다." class="btn btn-default"><div id="inside_div_fade{{ room.pk }}"><i class="fa fa-sign-in"></i></div></a></li>
              {% endif %}
              <!-- 자세히보기 --> 
              <li><a class="btn btn-default" data-toggle="modal" href="#room{{ room.pk }}" ><i class="fa fa-eye"></i></a></li>
            </ul>
            {% endif %}
          </div>
        </div>
        <div class="productCaption clearfix">
          <a href="{{ room.get_absolute_url }}">
            <h5>{{ room.subject }}</h5>
          </a>
          {% if 0 >= room.d_day or room.user|length == room.full %}
          <h3 style="font-size:14px; color:#a52a2a;">마감</h3>
          {% elif user.email in room.user or user.email == room.leader %}
          <h3>{{ room.user|length }}/{{ room.full }}&nbsp;&nbsp;<span style="color:#47bac1; font-size:14px;">이미 가입된 방입니다.</span></h3>
          {% elif 10 >= room.d_day %}
          <h3>{{ room.user|length }}/{{ room.full }}&nbsp;&nbsp;<span style="color:#47bac1; font-size:14px;">마감임박</span></h3>
          {% elif room.d_day > 10 %}
          <h3>{{ room.user|length }}/{{ room.full }}</h3>
          {% endif %}
        </div>
      </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#wish{{ room.pk }}, #wish_fade{{ room.pk }}').click(function(){
                $.ajax({
                    type: 'GET',
                    url : "{% url 'book:wish_room' slug_sub room.pk %}",
                    success: function(data){
                        $('#wish_div_fade{{ room.pk }}').html(data)
                    }
                });
            });
        });
        
        $(document).ready(function(){
            $('#inside_fade{{ room.pk }}').click(function(){
                $.ajax({
                    type: 'GET',
                    url : "{% url 'book:room_in' slug_sub room.pk %}",
                    success: function(data){
                        $('#inside_div_fade{{ room.pk }}').html(data)
                    }
                });
            });
        });
    </script>
    {% endfor %}
</div>

Reader/book/templates/book/uncheck_wish.html
<i class="fa fa-heart-o list"></i>

Reader/book/templates/book/uncheck_wish_book.html
<i class="fa fa-heart-o list"></i>