Reader/Reader/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView, HomeSearch, CreateUserModalView
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('account/', include('login.urls')),
    path('blog/', include('blog.urls')),
    path('chatbot/', include('chatbot.urls')),
    # path('model/', include('recommendation.urls')),
    path('profile/', include('myprofile.urls')),
    path('', HomeView.as_view(), name='home'),
    path('signup/', CreateUserModalView.as_view(), name='signup'),
    path('search/', HomeSearch, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Reader/blog/urls.py
from django.urls import path, re_path
from .views import PostList, PostSingle, AddComment, Sub, Update, Delete, SubUpdate, SubDelete, PostDelete, PostUpdate, PostSearch


app_name = 'blog'
urlpatterns = [
    path(r'sub/update/<int:pk>/', SubUpdate.as_view(), name='sub_update'),
    path(r'sub/delete/<int:pk>/', SubDelete, name='sub_delete'),
    path(r'update/<int:pk>/', Update.as_view(), name='comment_update'),
    path(r'delete/<int:pk>/', Delete, name='comment_delete'),
    path(r'sub/<int:pk>/', Sub.as_view(), name='sub'),
    path(r'comment/<int:pk>/', AddComment.as_view(), name='comment'),
    path(r'post/delete/<int:pk>/', PostDelete, name='post_delete'),
    path(r'post/update/<int:pk>/', PostUpdate.as_view(), name='post_update'),
    path(r'single/post/<int:pk>/', PostSingle.as_view(), name='single'),
    path(r'search/', PostSearch, name='search'),
    re_path(r'(?P<slug>[-\w]+)/(?P<page>\d+)/$', PostList.as_view(), name='blog_page'),
    re_path(r'(?P<slug>[-\w]+)/$', PostList.as_view(), name='blog'),
]

Reader/blog/models.py
from django.db import models
from taggit.managers import TaggableManager
from login.models import User
from login.fields import ThumbnailImageField
from book.models import MainCategory
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
# Create your models here.


class Post(models.Model):
    subject = models.TextField('SUBJECT', blank=True, null=True)
    explain = models.TextField('EXPLAIN')
    create_dt = models.DateTimeField('CREATE_DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY_DATE', auto_now=True)
    image = ThumbnailImageField(upload_to='blog/%Y/%m', blank=True, null=True)
    tag = TaggableManager(blank=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    category = models.ForeignKey(MainCategory, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'posts'
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-create_dt',)

    def get_comments_num(self):
        num = 0
        post = get_object_or_404(Post, id=self.id)
        comments = post.comment_set.all()
        for comment in comments:
            num += comment.subcomment_set.count() + 1

        return num

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse_lazy('blog:single', args=(self.id,))

    def get_previous(self):
        return self.get_previous_by_create_dt()

    def get_next(self):
        return self.get_next_by_create_dt()


class Comment(models.Model):
    explain = models.TextField('EXPLAIN')
    create_dt = models.DateTimeField('CREATE_DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY_DATE', auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'comments'
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        ordering = ('-create_dt',)


class SubComment(models.Model):
    explain = models.TextField('EXPLAIN')
    create_dt = models.DateTimeField('CREATE_DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY_DATE', auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'subs'
        verbose_name = 'sub'
        verbose_name_plural = 'subs'
        ordering = ('-create_dt',)

Reader/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import CreateView, DetailView, View
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Post, Comment, SubComment
from book.models import MainCategory

from book.room_views import return_category
from Reader.context_base import add_base_info
import os


# Create your views here.
class PostList(CreateView):
    model = Post
    context_object_name = 'form_post'
    fields = ['subject', 'explain', 'image', 'tag']
    template_name = 'blog/blog_list.html'
    success_url = None

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        self.success_url = reverse_lazy('blog:blog', args=(self.kwargs['slug'],))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_post'] = context['form']
        del context['form']

        context['categories'] = return_category()
        context['posts'] = Post.objects.filter(category__slug=self.kwargs['slug'])
        context['category_now'] = self.kwargs['slug']
        context['recents'] = Post.objects.all()[:3]

        p = Paginator(context['posts'], 5)
        if 'page' in self.kwargs.keys():
            page = p.page(self.kwargs['page'])
        else:
            page = p.page(1)
        context['posts'] = page.object_list
        context['page_obj'] = p
        context['present_page_obj'] = page
        context['present_page'] = page.number

        next_url = reverse_lazy('blog:blog', args=('총류',))
        return add_base_info(context, next_url)


class PostSingle(DetailView):
    model = Post
    template_name = 'blog/blog_single.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments_num'] = self.get_object().get_comments_num()
        next_url = reverse_lazy('blog:single', args=(self.kwargs['pk'],))
        return add_base_info(context, next_url)


def PostSearch(request):
    search = request.POST['search']
    posts = Post.objects.filter(Q(subject__icontains=search) |
                                Q(explain__icontains=search) |
                                Q(tag__name__in=[search])).distinct()
    context = {}
    context['posts'] = posts
    next_url = reverse_lazy('blog:blog', args=('총류',))
    return render(request, 'blog/blog_search.html', add_base_info(context, next_url))


def PostDelete(request, pk):
    post = get_object_or_404(Post, id=pk)
    redirect_url = reverse_lazy('blog:blog', args=(post.category.slug,))

    os.remove(post.image.path)
    os.remove(post.image.thumb_path)
    post.delete()
    return HttpResponseRedirect(redirect_url)


class PostUpdate(View):
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        subject = request.POST['subject']
        explain = request.POST['explain']

        post.subject = subject
        post.explain = explain
        post.save()
        return HttpResponseRedirect()


class AddComment(View):
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        explain = request.POST['contents']
        post.comment_set.create(explain=explain, owner=request.user)
        return HttpResponseRedirect()


class Sub(View):
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=self.kwargs['pk'])
        explain = request.POST['contents']
        comment.subcomment_set.create(explain=explain, owner=request.user)
        return HttpResponseRedirect()


class Update(View):
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=self.kwargs['pk'])
        explain = request.POST['contents']

        comment.explain = explain
        comment.save()
        return HttpResponseRedirect()


def Delete(request, pk):
    Comment.objects.get(id=pk).delete()
    return HttpResponseRedirect()


class SubUpdate(View):
    def post(self, request, *args, **kwargs):
        sub = get_object_or_404(SubComment, id=self.kwargs['pk'])
        explain = request.POST['contents']

        sub.explain = explain
        sub.save()
        return HttpResponseRedirect()


def SubDelete(request, pk):
    SubComment.objects.get(id=pk).delete()
    return HttpResponseRedirect()

Reader/blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block extra-style %}
<style>
 .txt_post {
    display:block;
    max-height:128px;
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>
{% endblock %}

{% block blog %}<li class="nav-item active">{% endblock %}

{% load static %}
    
{% load widget_tweaks %}
    
{% block banner %}{% endblock %}
    
{% block main %}
<!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="page-title">
                <h2>게시판</h2>
              </div>
            </div>
            <div class="col-md-6">
              <ol class="breadcrumb float-right">
                <li>
                  <a href="{% url 'home' %}">홈</a>
                </li>
                <li class="active">게시판</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix blogPage">
        <div class="container">
          <div class="row">
            <div class="col-lg-9 col-sm-12 order-lg-12">
              <div class="row">
                {% if posts|length == 0 %}
                <p style="color:#808080; font-size:20px;">아직 등록된 게시물이 없습니다.</p>
                {% else %}
                {% for post in posts %}
                <div class="col-sm-12">
                  <div class="thumbnail">
                    <a href="{{ post.get_absolute_url }}"><img class="mw-100" src="{{ post.image.url }}" alt="blog-image"></a>
                    <div class="caption">
                      <div class="row">
                        <div class="col-md-3 order-md-12">
                          <h5>Details</h5>
                          <ul class="list-unstyled">
                            <li><i class="fa fa-user" aria-hidden="true"></i>{{ post.owner.name }}</li>
                            <li><i class="fa fa-calendar" aria-hidden="true"></i>{{ post.create_dt|date:"Y년 m월 d일" }}</li>
                            <li><i class="fa fa-tags" aria-hidden="true"></i>
                            {% load taggit_templatetags2_tags %}
                            {% get_tags_for_object post as "tags" %}
                            {% for tag in tags %}
                            #{{ tag.name }}&nbsp;
                            {% endfor %}  
                            </li>
                            <li><i class="fa fa-envelope" aria-hidden="true"></i>{{ post.get_comments_num }}개의 댓글</li>
                          </ul>
                        </div>
                        <div class="col-md-9 order-md-1">
                          <h3><a href="{{ post.get_absolute_url }}">{{ post.subject }}</a></h3>
                          <p><span class="txt_post">{{ post.explain }}</span><br>
                            <a href="{{ post.get_absolute_url }}"><span style="color:#47bac1;">더보기 &raquo;</span></a></p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
                {% endif %}
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="text-left">
                    <ul class="pagination">
                      {% if present_page_obj.has_previous %}
                      <li>
                        <a href="{% url 'blog:blog_page' category_now present_page_obj.previous_page_number %}" aria-label="Next">
                          <span aria-hidden="true">&laquo;</span>
                        </a>
                      </li>
                      {% endif %}
                      {% for idx in page_obj.page_range %}
                      {% if idx == present_page %}
                      <li class="active"><a href="#">{{ idx }}</a></li>
                      {% else %}
                      <li><a href="{% url 'blog:blog_page' category_now idx %}">{{ idx }}</a></li>
                      {% endif %}
                      {% endfor %}
                      {% if present_page_obj.has_next %}
                      <li>
                        <a href="{% url 'blog:blog_page' category_now present_page_obj.next_page_number %}" aria-label="Next">
                          <span aria-hidden="true">&raquo;</span>
                        </a>
                      </li>
                      {% endif %}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-sm-12 order-lg-1 sideBar">
              {% if user.is_active %}
              <a href="#create_post" data-toggle="modal"><button class="btn btn-primary-outlined" type="submit" style="width:100%; margin-bottom:10px;">게시물 올리기</button></a>
              {% endif %}
              <form class="input-group" action="{% url 'blog:search' %}" method="post" role="form">{% csrf_token %}
                <input name="search" type="text" class="form-control" placeholder="검색" aria-describedby="basic-addon2">
                <button type="submit" class="input-group-addon" id="basic-addon2"><i class="fa fa-search"></i></button>
              </form>
              <div class="panel panel-default">
                <div class="panel-heading">도서 분류</div>
                <div class="panel-body">
                  <ul class="list-unstyle sidebar-list">
                    {% for category in categories %}
                    {% if category.slug == category_now %}
                    <li><a style="color:#47bac1;" href="{% url 'blog:blog' category %}"><i class="fa fa-caret-right" aria-hidden="true"></i>{{ category }}</a></li>
                    {% else %}
                    <li><a href="{% url 'blog:blog' category %}"><i class="fa fa-caret-right" aria-hidden="true"></i>{{ category }}</a></li>
                    {% endif %}
                    {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="panel panel-default recentBlogPosts">
                <div class="panel-heading">최근 게시물</div>
                <div class="panel-body">
                  {% for recent in recents %}
                  <div class="media">
                    <a class="media-left" href="{{ recent.get_absolute_url }}">
                      <img class="media-object" style="height:70px; width:70px;" src="{{ recent.image.url }}" alt="Image">
                    </a>
                    <div class="media-body">
                      <h4 class="media-heading"><a href="{{ recent.get_absolute_url }}">{{ recent.subject }}</a></h4>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>{{ recent.create_dt|date:"Y년 m월 d일" }}</p>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    
      <!-- 방 만들기 -->
    <div class="modal fade quick-view" id="create_post" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header justify-content-center">
					<h3 class="modal-title">게시물 올리기</h3>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
                    <form enctype="multipart/form-data" action="." method="POST" class="form-horizontal">
                    {% csrf_token %}
					<div class="form-group">
                        <label for="">제목</label>
						{% render_field form_post.subject rows="1" class="form-control" placeholder="제목을 적어주세요."  required="" %}
					</div>
					<div class="form-group">
                        <label for="">내용</label>
						{% render_field form_post.explain rows="5" class="form-control" placeholder="내용을 적어주세요." required="" %}
					</div>
                    <div class="form-group">
                        <label for="">이미지</label>
						{% render_field form_post.image class="form-control" required="" %}
					</div>
                    <div class="form-group">
                        <label for="">태그</label>
                        {% render_field form_post.tag class="form-control" placeholder="게시물을 설명할 수 있는 대표적인 단어들로 태그를 달아주세요." required="" %}
					</div>
                    <input type="submit" class="btn btn-primary btn-block" value="게시물 올리기">
                    </form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

<!-- ajax에서의 POST 통신을 위해 csrf 토큰을 넘겨줌 -->
{% block extra-script %}
{% endblock %}

Reader/blog/templates/blog/blog_search.html
{% extends "base.html" %}

{% block extra-style %}
<style>
 .txt_post {
    display:block;
    max-height:128px;
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>
{% endblock %}

{% block blog %}<li class="nav-item active">{% endblock %}

{% load static %}
    
{% load widget_tweaks %}
    
{% block banner %}{% endblock %}
    
{% block main %}
<!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="page-title">
                <h2>검색결과</h2>
              </div>
            </div>
            <div class="col-md-6">
              <ol class="breadcrumb float-right">
                <li>
                  <a href="index.html">Home</a>
                </li>
                <li class="active">검색결과</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix blogPage">
        <div class="container">
          <div class="row">
            {% if posts|length == 0 %}
            <p style="color:#808080; font-size:20px;">검색결과가 없습니다.</p>
            {% else %}
            {% for post in posts %}
            <div class="col-sm-12">
              <div class="thumbnail">
                <a href="{{ post.get_absolute_url }}"><img class="mw-100" src="{{ post.image.url }}" alt="blog-image"></a>
                  <div class="caption">
                    <div class="row">
                      <div class="col-md-3 order-md-12">
                        <h5>Details</h5>
                        <ul class="list-unstyled">
                          <li><i class="fa fa-user" aria-hidden="true"></i>{{ post.owner.name }}</li>
                          <li><i class="fa fa-calendar" aria-hidden="true"></i>{{ post.create_dt }}</li>
                          <li><i class="fa fa-tags" aria-hidden="true"></i>
                          {% load taggit_templatetags2_tags %}
                          {% get_tags_for_object post as "tags" %}
                          {% for tag in tags %}
                          #{{ tag.name }}&nbsp;
                          {% endfor %}  
                          </li>
                        <li><i class="fa fa-envelope" aria-hidden="true"></i>{{ post.get_comments_num }}개의 댓글</li>
                      </ul>
                    </div>
                    <div class="col-md-9 order-md-1">
                      <h3><a href="{{ post.get_absolute_url }}">{{ post.subject }}</a></h3>
                      <p><span class="txt_post">{{ post.explain }}</span><br>
                      <a href="{{ post.get_absolute_url }}"><span style="color:#47bac1;">더보기 &raquo;</span></a></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% endif %}
          </div>
        </div>
      </section>
{% endblock %}