Reader/Reader/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView, HomeSearch, CreateUserModalView
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('account/', include('login.urls')),
    path('blog/', include('blog.urls')),
    path('chatbot/', include('chatbot.urls')),
    # path('model/', include('recommendation.urls')),
    path('profile/', include('myprofile.urls')),
    path('', HomeView.as_view(), name='home'),
    path('signup/', CreateUserModalView.as_view(), name='signup'),
    path('search/', HomeSearch, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Reader/blog/urls.py
from django.urls import path, re_path
from .views import PostList, PostSingle, AddComment, Sub, Update, Delete, SubUpdate, SubDelete, PostDelete, PostUpdate, PostSearch


app_name = 'blog'
urlpatterns = [
    path(r'sub/update/<int:pk>/', SubUpdate.as_view(), name='sub_update'),
    path(r'sub/delete/<int:pk>/', SubDelete, name='sub_delete'),
    path(r'update/<int:pk>/', Update.as_view(), name='comment_update'),
    path(r'delete/<int:pk>/', Delete, name='comment_delete'),
    path(r'sub/<int:pk>/', Sub.as_view(), name='sub'),
    path(r'comment/<int:pk>/', AddComment.as_view(), name='comment'),
    path(r'post/delete/<int:pk>/', PostDelete, name='post_delete'),
    path(r'post/update/<int:pk>/', PostUpdate.as_view(), name='post_update'),
    path(r'single/post/<int:pk>/', PostSingle.as_view(), name='single'),
    path(r'search/', PostSearch, name='search'),
    re_path(r'(?P<slug>[-\w]+)/(?P<page>\d+)/$', PostList.as_view(), name='blog_page'),
    re_path(r'(?P<slug>[-\w]+)/$', PostList.as_view(), name='blog'),
]

Reader/myprofile/urls.py
from django.urls import path
from .views import Profile, WishList, WishDelete, RoomList


app_name = 'profile'
urlpatterns = [
    path('', Profile.as_view(), name='profile'),
    path('wishlist/', WishList.as_view(), name='wishlist'),
    path('room/', RoomList.as_view(), name='room'),
    path('delete/<int:pk>/', WishDelete.as_view(), name='delete'),
]

Reader/myprofile/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import UpdateView, ListView, View, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from book.models import Book
from login.models import User

from firebase.models import Room
from firebase.firebase import db
import os
import datetime
import time


# Create your views here.
class Profile(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['name', 'sosok', 'image']
    template_name = 'myprofile/profile.html'
    success_url = reverse_lazy('profile:profile')
    image_url = None
    image_path = None
    image_thumb_path = None

    def form_valid(self, form):
        if self.image_url and form.instance.image.url != self.image_url:
            os.remove(self.image_path)
            os.remove(self.image_thumb_path)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slug'] = '총류'
        return context

    def get_object(self):
        if self.request.user.image:
            self.image_url = self.request.user.image.url
            self.image_path = self.request.user.image.path
            self.image_thumb_path = self.request.user.image.thumb_path
        return self.request.user


class WishList(LoginRequiredMixin, ListView):
    model = Book
    template_name = 'myprofile/wishlist.html'
    context_object_name = 'books'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slug'] = '총류'
        return context

    def get_queryset(self):
        return Book.objects.filter(wish=self.request.user)


class RoomList(LoginRequiredMixin, TemplateView):
    template_name = 'myprofile/room.html'

    def get_context_data(self, **kwargs):
        context = {}
        context['slug'] = '총류'

        context['rooms'] = []
        from firebase_admin import firestore
        rooms = db.collection(u'all').order_by(u'create', direction=firestore.Query.DESCENDING).stream()

        for room in rooms:
            room_obj = Room.from_dict(room.to_dict())
            if self.request.user.email in room_obj.user:
                context['rooms'].append(room_obj)
                today = datetime.date.today()
                target = context['rooms'][-1].duedate
                local = time.localtime(target)
                target = datetime.date(local.tm_year, local.tm_mon, local.tm_mday)
                context['rooms'][-1].d_day = (target-today).days

                target = context['rooms'][-1].deadline
                local = time.localtime(target)
                target = datetime.date(local.tm_year, local.tm_mon, local.tm_mday)
                context['rooms'][-1].d_dead = (target-today).days
        return context


class WishDelete(View):
    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, id=self.kwargs['pk'])
        self.request.user.book_set.remove(book)

        context = {}
        context['books'] = Book.objects.filter(wish=self.request.user)
        return render(request, 'myprofile/delete.html', context)

Reader/myprofile/templates/myprofile/delete.html
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>책 제목</th>
      <th>책 코드</th>
      <th>태그</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% if books|length == 0 %}
    <p>좋아요를 누른 도서가 없습니다.</p>
    {% else %}
    {% for book in books %}
    <tr>
      <td class="">
        <button type="button" id="delete{{ book.id }}" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </td>
      <td>{{ book.name }}</td>
      <td>{{ book.code }}</td>
      <td>
      {% load taggit_templatetags2_tags %}
      {% get_tags_for_object book as "tags" %}
      {% for tag in tags %}
      #{{ tag.name }}&nbsp;
      {% endfor %}
      </td>
      <td>
        <a href="{{ book.get_absolute_url }}" class="btn btn-sm btn-secondary-outlined">자세히보기</a>
      </td>
    </tr>
    <script src="https://code.jquery.com/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#delete{{ book.id }}').click(function(){
                $.ajax({
                    type: 'GET',
                    url : "{% url 'profile:delete' book.id %}",
                    success: function(data){
                        $('.table-responsive').html(data)
                    }
                });
            });
        });
    </script>
    {% endfor %}
    {% endif %}
  </tbody>
</table>

Reader/myprofile/templates/myprofile/profile.html
{% extends "base.html" %}

{% load static %}
    
{% load widget_tweaks %}

{% block extra-style %}
<style>
    a {
        color:#47bac1;
    }
    a:hover {
        color:#008080; !important
    }
</style>
{% endblock %}

{% block profile %}<li class="nav-item dropdown active">{% endblock %}
    
{% block banner %}{% endblock %}
    
{% block main %}
<!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="page-title">
                <h2>나의 프로필</h2>
              </div>
            </div>
            <div class="col-md-6">
              <ol class="breadcrumb float-right">
                <li>
                  <a href="{% url 'home' %}">홈</a>
                </li>
                <li class="active">프로필</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix userProfile">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div class="btn-group" role="group" aria-label="...">
                <a href="{% url 'profile:profile' %}" class="btn btn-default active"><i class="fa fa-user" aria-hidden="true"></i>프로필</a>
                <a href="{% url 'profile:room' %}" class="btn btn-default"><i class="fa fa-list" aria-hidden="true"></i>나의 독서방</a>
                <a href="{% url 'profile:wishlist' %}" class="btn btn-default"><i class="fa fa-heart" aria-hidden="true"></i>좋아요</a>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="innerWrapper profile">
                <div class="orderBox">
                  <h2>프로필</h2>
                </div>
                <div class="row">
                  <div class="col-md-4 col-lg-3 col-xl-2 col-12">
                    <div class="thumbnail">
                        {% if not user.image %}
                        <img src="{% static 'assets/img/blog/avatar.jpg' %}" style="border-radius:7px;" alt="profile-image">
                        {% else %}
                        <img src="{{ user.image.url }}" style="border-radius:7px;" alt="profile-image">
                        {% endif %}
                    </div>
                  </div>
                  <div class="col-md-8 col-lg-9 col-xl-10 col-12">
                      <form enctype="multipart/form-data" action="." method="POST" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group row">
                          <label for="" class="col-md-3 control-label">이메일</label>
                          <div class="col-md-7">
                            <input type="text" class="form-control" id="" placeholder="{{ user.email }}" disabled>
                          </div>
                        </div>
                        <div class="form-group row">
                          <label for="" class="col-md-3 control-label">프로필 이미지</label>
                          <div class="col-md-7">
                            {% render_field form.image class="form-control" style="height:75px;" %}
                          </div>
                        </div>
                        <div class="form-group row">
                          <label for="" class="col-md-3 control-label">이름</label>
                          <div class="col-md-9">
                            {% render_field form.name class="form-control" %}
                          </div>
                        </div>
                        <div class="form-group row">
                          <label for="" class="col-md-3 control-label">소속</label>
                          <div class="col-md-9">
                            {% render_field form.sosok class="form-control" %}
                          </div>
                        </div>
                        <div class="form-group row">
                          <div class=" col-md-12 ">
                            <input type="submit" class="btn btn-primary float-right" value="저장하기"/>
                          </div>
                        </div>
                      </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

Reader/myprofile/templates/myprofile/room.html
{% extends "base.html" %}

{% block extra-style %}{% endblock %}

{% block profile %}<li class="nav-item dropdown active">{% endblock %}

{% load static %}
    
{% block banner %}{% endblock %}
    
{% block main %}
<!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="page-title">
                <h2>나의 독서방</h2>
              </div>
            </div>
            <div class="col-md-6">
              <ol class="breadcrumb float-right">
                <li>
                  <a href="{% url 'home' %}">홈</a>
                </li>
                <li class="active">나의 독서방</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix userProfile">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="btn-group" role="group" aria-label="...">
                <a href="{% url 'profile:profile' %}" class="btn btn-default"><i class="fa fa-user" aria-hidden="true"></i>프로필</a>
                <a href="{% url 'profile:room' %}" class="btn btn-default active"><i class="fa fa-list" aria-hidden="true"></i>나의 독서방</a>
                <a href="{% url 'profile:wishlist' %}" class="btn btn-default"><i class="fa fa-heart" aria-hidden="true"></i>좋아요</a>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="innerWrapper">
                <div class="orderBox">
                  <h2>나의 독서방</h2>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>방 제목</th>
                          <th>인원수</th>
                          <th>D-day</th>
                          <th>책 제목</th>
                          <th>상태</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for room in rooms %}
                        <tr>
                          <td>{{ room.subject }}</td>
                          <td>{{ room.get_user_num }}명</td>
                          {% if room.d_dead > 0 %}
                          <td>D-{{ room.d_dead }}</td>
                          {% else %}
                          <td><span style="color:#a52a2a;">마감</span></td>
                          {% endif %}
                          <td>{{ room.get_book_title }}</td>
                          {% if 0 >= room.d_dead %}
                          <td><span class="badge badge-success">완료</span></td>
                          {% elif 0 >= room.d_day or room.get_user_num >= room.full %}
                          <td><span class="badge badge-primary">진행중</span>&nbsp;<span class="badge badge-danger">인원모집 마감</span></td>
                          {% else %}
                          <td><span class="badge badge-primary">진행중</span></td>
                          {% endif %}
                          <td><a href="{{ room.get_absolute_url }}" class="btn btn-sm btn-secondary-outlined">자세히보기</a></td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

Reader/myprofile/templates/myprofile/wishlist.html
{% extends "base.html" %}

{% block extra-style %}{% endblock %}

{% block profile %}<li class="nav-item dropdown active">{% endblock %}

{% load static %}
    
{% block banner %}{% endblock %}
    
{% block main %}
    <!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="page-title">
                <h2>좋아요를 누른 책 리스트</h2>
              </div>
            </div>
            <div class="col-md-6">
              <ol class="breadcrumb pull-right">
                <li>
                  <a href="{% url 'home' %}">홈</a>
                </li>
                <li class="active">좋아요를 누른 책 리스트</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix userProfile">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div class="btn-group" role="group" aria-label="...">
                <a href="{% url 'profile:profile' %}" class="btn btn-default"><i class="fa fa-user" aria-hidden="true"></i>프로필</a>
                <a href="{% url 'profile:room' %}" class="btn btn-default"><i class="fa fa-list" aria-hidden="true"></i>나의 독서방</a>
                <a href="{% url 'profile:wishlist' %}" class="btn btn-default active"><i class="fa fa-heart" aria-hidden="true"></i>좋아요</a>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="innerWrapper">
                <div class="orderBox myAddress wishList">
                  <h2>좋아요를 누른 책 리스트</h2>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th></th>
                          <th>책 제목</th>
                          <th>책 코드</th>
                          <th>태그</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% if books|length == 0 %}
                        <p>좋아요를 누른 도서가 없습니다.</p>
                        {% else %}
                        {% for book in books %}
                        <tr>
                          <td class="">
                            <button type="button" id="delete{{ book.id }}" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          </td>
                          <td>{{ book.name }}</td>
                          <td>{{ book.code }}</td>
                          <td>
                          {% load taggit_templatetags2_tags %}
                          {% get_tags_for_object book as "tags" %}
                          {% for tag in tags %}
                          #{{ tag.name }}&nbsp;
                          {% endfor %}
                          </td>
                          <td>
                            <a href="{{ book.get_absolute_url }}" class="btn btn-sm btn-secondary-outlined">자세히보기</a>
                          </td>
                        </tr>
                        <script src="https://code.jquery.com/jquery.min.js"></script>
                        <script type="text/javascript">
                            $(document).ready(function(){
                                $('#delete{{ book.id }}').click(function(){
                                    $.ajax({
                                        type: 'GET',
                                        url : "{% url 'profile:delete' book.id %}",
                                        success: function(data){
                                            $('.table-responsive').html(data)
                                        }
                                    });
                                });
                            });
                        </script>
                        {% endfor %}
                        {% endif %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}